export const PERMISSIONS = {
    // Global & Financials
    VIEW_GLOBAL_STATS: 'VIEW_GLOBAL_STATS',
    VIEW_FINANCIALS: 'VIEW_FINANCIALS',
    MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
    VIEW_PERSONNEL: 'VIEW_PERSONNEL',
    
    // User & Profile
    MANAGE_USERS: 'MANAGE_USERS',
    VIEW_USER_DETAILS: 'VIEW_USER_DETAILS',
    
    // Pastoral & Spiritual
    VIEW_PASTORAL_PORTAL: 'VIEW_PASTORAL_PORTAL',
    APPROVE_BAPTISM: 'APPROVE_BAPTISM',
    APPROVE_DEDICATION: 'APPROVE_DEDICATION',
    MANAGE_APPOINTMENTS: 'MANAGE_APPOINTMENTS',
    
    // Departmental logic
    VIEW_DEPARTMENT: 'VIEW_DEPARTMENT',
    MANAGE_DEPARTMENT_PROJECTS: 'MANAGE_DEPARTMENT_PROJECTS',
    MANAGE_DEPARTMENT_EVENTS: 'MANAGE_DEPARTMENT_EVENTS',
    MANAGE_DEPARTMENT_PLANS: 'MANAGE_DEPARTMENT_PLANS',
    CREATE_ANNOUNCEMENTS: 'CREATE_ANNOUNCEMENTS',
    
    // System & Technical
    ACCESS_WATUA: 'ACCESS_WATUA',
    MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
    VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS'
} as const;
