export const PERMISSIONS = {
    // Global & Financials
    VIEW_GLOBAL_STATS: 'VIEW_GLOBAL_STATS',
    VIEW_FINANCIALS: 'VIEW_FINANCIALS',
    MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
    VIEW_PERSONNEL: 'VIEW_PERSONNEL',
    
    // User & Profile
    MANAGE_USERS: 'MANAGE_USERS',
    VIEW_USER_DETAILS: 'VIEW_USER_DETAILS',
    
    // Pastoral & Spiritual
    VIEW_PASTORAL_PORTAL: 'VIEW_PASTORAL_PORTAL',
    APPROVE_BAPTISM: 'APPROVE_BAPTISM',
    APPROVE_DEDICATION: 'APPROVE_DEDICATION',
    MANAGE_APPOINTMENTS: 'MANAGE_APPOINTMENTS',
    
    // Operational & Departmental
    VIEW_DEPARTMENT: 'VIEW_DEPARTMENT',
    MANAGE_DEPARTMENT_PROJECTS: 'MANAGE_DEPARTMENT_PROJECTS',
    MANAGE_DEPARTMENT_EVENTS: 'MANAGE_DEPARTMENT_EVENTS',
    MANAGE_DEPARTMENT_PLANS: 'MANAGE_DEPARTMENT_PLANS',
    CREATE_ANNOUNCEMENTS_LOCAL: 'CREATE_ANNOUNCEMENTS_LOCAL',
    CREATE_ANNOUNCEMENTS_GLOBAL: 'CREATE_ANNOUNCEMENTS_GLOBAL',
    
    // System & Technical
    ACCESS_WATUA: 'ACCESS_WATUA',
    VIEW_COVENANT_PARTNERSHIPS: 'VIEW_COVENANT_PARTNERSHIPS',
    MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
    VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS'
} as const;

export type PermissionCode = keyof typeof PERMISSIONS;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
    MEMBER: [],
    DEPARTMENT_LEADER: ['VIEW_DEPARTMENT', 'MANAGE_DEPARTMENT_PROJECTS', 'MANAGE_DEPARTMENT_EVENTS', 'MANAGE_DEPARTMENT_PLANS', 'CREATE_ANNOUNCEMENTS_LOCAL'],
    PASTOR: ['VIEW_PASTORAL_PORTAL', 'APPROVE_BAPTISM', 'APPROVE_DEDICATION', 'MANAGE_APPOINTMENTS'],
    SECRETARY: ['VIEW_GLOBAL_STATS', 'VIEW_PERSONNEL', 'MANAGE_APPOINTMENTS', 'VIEW_COVENANT_PARTNERSHIPS'],
    SYSTEM_ADMIN: ['VIEW_GLOBAL_STATS', 'VIEW_FINANCIALS', 'MANAGE_DEPARTMENTS', 'MANAGE_USERS', 'VIEW_PERSONNEL', 'CREATE_ANNOUNCEMENTS_GLOBAL', 'VIEW_COVENANT_PARTNERSHIPS'],
    SUPER_ADMIN: Object.keys(PERMISSIONS) as PermissionCode[],
    WATUA: Object.keys(PERMISSIONS) as PermissionCode[]
};
